# Generated by Django 2.2.1 on 2019-08-05 03:05

from django.db import migrations, models
import query.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysisFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.FileField(upload_to='')),
                ('distanceEdit', models.FileField(upload_to=query.models.get_upload_path)),
                ('distanceJukesCantor', models.FileField(upload_to=query.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='inputQueryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biologicalName', models.CharField(max_length=100)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('fileExtension', models.CharField(max_length=10)),
                ('collectionName', models.CharField(max_length=200)),
                ('fastQ', models.FileField(upload_to=query.models.get_upload_path, validators=[query.models.validate_file_extension])),
            ],
        ),
    ]
