# Generated by Django 2.2.1 on 2019-08-05 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skmerApp', '0001_initial'),
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputqueryfile',
            name='createUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skmerApp.skmerUser'),
        ),
        migrations.AddField(
            model_name='analysisfile',
            name='createInputFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.inputQueryFile'),
        ),
        migrations.AddField(
            model_name='analysisfile',
            name='createUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skmerApp.skmerUser'),
        ),
    ]
