# Generated by Django 2.2.1 on 2019-08-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20190804_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputqueryfile',
            name='biologicalName',
            field=models.CharField(blank=True, default='unnamed', max_length=100),
        ),
        migrations.AlterField(
            model_name='inputqueryfile',
            name='collectionName',
            field=models.CharField(blank=True, default='unnamed', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputqueryfile',
            name='fileExtension',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
